apiVersion: v1
kind: Template
metadata:
  name: verwerkingsregister
objects:
- apiVersion: v1
    kind: BuildConfig
    metadata:
      name: verwerkingsregister
      namespace: webcomponentsqa
      labels:
        app: verwerkingsregister
        component: verwerkingsregister
    spec:
      failedBuildsHistoryLimit: 2
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: verwerkingsregister:latest
      postCommit: {}
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 25Mi
      runPolicy: Serial
      source:
        git:
          ref: master
          uri: git@github.com:StadGent/nuxt_site_verwerkingsregister.git
        sourceSecret:
          name: digipolisgent-ci
        type: Git
      strategy:
        sourceStrategy:
          env:
            - name: HOST
              value: 0.0.0.0
            - name: DEPLOY_ENV
              value: qa
            - name: NODE_VERSION_URL
              value: https://semver.io/node/resolve/9.x
          from:
            kind: ImageStreamTag
            name: nodejs-8-rhel7:latest
        type: Source
      successfulBuildsHistoryLimit: 2
      triggers: []
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: verwerkingsregister
    namespace: webcomponentsqa
    labels:
      app: verwerkingsregister
      component: verwerkingsregister
  spec:
    replicas: 1
    selector:
      app: verwerkingsregister
      component: verwerkingsregister
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        name: verwerkingsregister
        namespace: webcomponentsqa
        labels:
          app: verwerkingsregister
          component: verwerkingsregister
      spec:
        containers:
        - env:
          - name: HOST
            value: 0.0.0.0
          - name: DEPLOY_ENV
            value: qa
          - name: NODE_VERSION_URL
            value: https://semver.io/node/resolve/9.x
          image: docker-registry.default.svc:5000/webcomponentsdv/verwerkingsregister:accepted_dv
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          name: verwerkingsregister
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: 
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 10m
              memory: 25Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
- apiVersion: v1
  kind: Service
  metadata:
    name: verwerkingsregister
    namespace: webcomponentsqa
    labels:
      app: verwerkingsregister
      component: verwerkingsregister
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: verwerkingsregister
      component: verwerkingsregister
    sessionAffinity: None
    type: ClusterIP
